### ISSUE TITLE
ssl support for LANCommander.Lancher.

### ISSUE THREAD

**Issue by MrCaffeen** [LANCommander/LANCommander#101]
Basically if we put lancommander behind a SSL proxy nginx reverse proxy with a certificate. can we have the client able to communicate with the server? or is it only supported directly using ports 1337 using http only?

would be good to have that extra option to run SSL if we could. also would be good to have the server able to run on a SSL port if we choose to do so as well. I know this may add some complexity to the project, but hopefully not too much our of reach.

**Comment by MrCaffeen** [comment]
this is what we see from the client app logs
`2024-09-16 22:07:37.681 +10:00 [ERR] The SSL connection could not be established, see inner exception.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClientExtensions.ExecuteAsync[T](IRestClient client, RestRequest request, CancellationToken cancellationToken)
   at LANCommander.SDK.Client.AuthenticateAsync(String username, String password, Boolean ignoreVersion)
   at LANCommander.Launcher.Services.ProfileService.Login(String serverAddress, String username, String password)
   at LANCommander.Launcher.UI.Authenticate.Login.OnFinish(EditContext editContext)
2024-09-16 22:09:24.224 +10:00 [ERR] The SSL connection could not be established, see inner exception.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at RestSharp.ResponseThrowExtension.ThrowIfError(RestResponse response)
   at RestSharp.RestClient.ExecuteAsync(RestRequest request, CancellationToken cancellationToken)
   at RestSharp.RestClientExtensions.ExecuteAsync[T](IRestClient client, RestRequest request, CancellationToken cancellationToken)
   at LANCommander.SDK.Client.AuthenticateAsync(String username, String password, Boolean ignoreVersion)
   at LANCommander.Launcher.Services.ProfileService.Login(String serverAddress, String username, String password)
   at LANCommander.Launcher.UI.Authenticate.Login.OnFinish(EditContext editContext)`

**Comment by MrCaffeen** [comment]
could we be hitting this from a windows 10 computer as the launcher host

https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5/28333370#28333370

**Comment by pathartl** [comment]
SSL works fine, make sure your nginx proxy is configured to use TLS 1.3 and TLS 1.2:
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu

To get the web UI to work as well the reverse proxy must support websockets.
