### ISSUE TITLE
Linux Servers Scripts add executable

### ISSUE THREAD

**Issue by miketweaver** [LANCommander/LANCommander#69]
The Server's scripts feature only allows you to add powershell scripts. This doesn't really account for Linux usage.

It would be nice if, instead of running a powershell, there was an option to run an executable & arguments, similar to starting the server.

![image](https://github.com/LANCommander/LANCommander/assets/5581855/607ce510-cc7d-4ed7-9a24-1205419478a6)

**Comment by miketweaver** [comment]
This would be useful because the server Scripts, by default, run powershell and they're just broken on Linux.

```
2024-05-27 00:50:56.6398|ERROR|LANCommander.Services.ServerProcessService|Error running script ""Stop CURSED HALO"" for server ""Cursed Halo""|System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at LANCommander.SDK.PowerShell.PowerShellScript..ctor()
   at LANCommander.Services.ServerProcessService.<>c__DisplayClass26_0.<StopServer>b__0()
   ```
   
   It looks like the constructor for `PowerShellScript();` just won't work on Linux.
   
   https://github.com/LANCommander/LANCommander/blob/66ae9f175c03397cfd3902debe62f6c8fe6547ef/LANCommander/Services/ServerProcessService.cs#L291C42-L291C65

**Comment by pathartl** [comment]
The server currently uses the same method to execute PowerShell scripts that the Playnite extension uses. For most projects it would make the most sense to have the scripting runtime embedded in the application. Because of limitations with Playnite's built in runtime, namely not being able to run scripts with elevated privileges as well as being out of date, scripts are currently run by feeding their path to `PowerShell.exe`, which obviously doesn't exist in Linux.

I would like to support scripts for other runtimes/shells in the future, but right now with the workload I can only focus on supporting PowerShell. That being said, with 1.0.0 there will be a major change to how scripts are executed on the server and new client where PowerShell scripts will execute as part of the application's runtime, which I believe will result in support for scripts on any platform that supports .NET 8.

I'm hoping to get something more concrete over the next few weeks.

**Comment by pathartl** [comment]
Closing. A PowerShell scripting engine has been built into the launcher for some time, so there is no reliance on external PowerShell runtimes.
